common:
  timezone_offset: "+01:00"
  hostname: "edge.vm"

suspicious_login:
  log_path: "/var/log/auth.log"
  sudo_tee: true
  user: "test01"
  sshd_pid: 1169457
  fail_port: 1045
  success_port: 60850
  key_fingerprint_fail: "ED25519 SHA256:A."
  key_fingerprint_success: "ED25519 SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  ip_pool:
    - "8.8.8.8"
    - "1.0.136.99"
    - "89.31.143.90"
    - "47.91.170.222"
    - "150.95.255.38"
    - "84.32.84.32"
  window_seconds: 60

geoip_detection:
  log_path: "/var/log/auth.log"
  sudo_tee: true
  user: "test01"
  sshd_pid: 1169457
  success_port: 60850
  ip: "8.8.8.8"
  key_fingerprint_success: "ED25519 SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

log_volume:
  target_dir: "/var/log"
  spike_filename: "ratf_log_volume_spike.log"

  steps: 10
  start_bytes: 268435456       # 256 MB
  growth_factor: 1.5
  sleep_seconds: 1

  max_total_bytes: 10000000000   # 10.0 GB
  max_step_bytes: 1500000000   # 1.5 GB

  cleanup_minutes: 5
