settings:
  digits: 3
  itemformat: markdown
  parent: MRS
  prefix: SRS
  sep: '-'

attributes:
  defaults:
    dependence: []
    status: ''
    importance: ''
    urgency: ''
    difficulty: ''
    risk: ''
    outlay: ''
    type: ''
    rationale: ''
    version: ''
    release: 'Alpha'
    text: |
      Description

      ## Rationale
      - 
      
      ## Acceptance criteria
  reviewed:
  - dependence
  - status
  - importance
  - urgency
  - risk
  - outlay
  - type
  - version
  publish:
    - status
    - importance
    - urgency
    - risk
    - type
    - version
