settings:
  digits: 3
  itemformat: yaml
  parent: MRS
  prefix: SRS
  sep: '-'

attributes:
  defaults:
    acceptance: 'Successful validation according to the corresponding test case specification'
    dependence: []
    status: ''
    importance: ''
    urgency: ''
    difficulty: ''
    risk: ''
    outlay: ''
    type: ''
    rationale: ''
    version: ''
    release: 'Alpha'
  reviewed:
  - acceptance
  - dependence
  - status
  - importance
  - urgency
  - risk
  - outlay
  - type
  - rationale
  - version
  publish:
    - acceptance
    - dependence
    - status
    - importance
    - urgency
    - risk
    - outlay
    - type
    - rationale
    - version
