
# MTAD_GAT config keys
MTAD_GAT_WINDOW_SIZE='window_size'
MTAD_GAT_SPEC_RES='spec_res'
MTAD_GAT_KERNEL_SIZE='kernel_size'
MTAD_GAT_USE_GATV2='use_gatv2'
MTAD_GAT_FEAT_GAT_EMBED_DIM='feat_gat_embed_dim'
MTAD_GAT_TIME_GAT_EMBED_DIM='time_gat_embed_dim'
MTAD_GAT_GRU_N_LAYERS='gru_n_layers'
MTAD_GAT_GRU_HID_DIM='gru_hid_dim'
MTAD_GAT_FC_N_LAYERS='fc_n_layers'
MTAD_GAT_FC_HID_DIM='fc_hid_dim'
MTAD_GAT_RECON_N_LAYERS='recon_n_layers'
MTAD_GAT_RECON_HID_DIM='recon_hid_dim'
MTAD_GAT_ALPHA='alpha'
MTAD_GAT_EPOCHS='epochs'
MTAD_GAT_VAL_SPLIT='val_split'
MTAD_GAT_BS='bs'
MTAD_GAT_INIT_LR='init_lr'
MTAD_GAT_SHUFFLE_DATASET='shuffle_dataset'
MTAD_GAT_DROPOUT='dropout'
MTAD_GAT_USE_CUDA='use_cuda'
MTAD_GAT_PRINT_EVERY='print_every'
MTAD_GAT_LOG_TENSORBOARD='log_tensorboard'
MTAD_GAT_SCALE_SCORES='scale_scores'
MTAD_GAT_USE_MOV_AV='use_mov_av'
MTAD_GAT_GAMMA='gamma'
MTAD_GAT_LEVEL='level'
MTAD_GAT_Q='q'
MTAD_GAT_DYNAMIC_POT='dynamic_pot'
MTAD_GAT_TYPE='type'
MTAD_GAT_DEFAULT='default'
MTAD_GAT_THREADS='threads'

MTAD_GAT_ALL:list[str] = [
    MTAD_GAT_WINDOW_SIZE,
    MTAD_GAT_SPEC_RES,
    MTAD_GAT_KERNEL_SIZE,
    MTAD_GAT_USE_GATV2,
    MTAD_GAT_FEAT_GAT_EMBED_DIM,
    MTAD_GAT_TIME_GAT_EMBED_DIM,
    MTAD_GAT_GRU_N_LAYERS,
    MTAD_GAT_GRU_HID_DIM,
    MTAD_GAT_FC_N_LAYERS,
    MTAD_GAT_FC_HID_DIM,
    MTAD_GAT_RECON_N_LAYERS,
    MTAD_GAT_RECON_HID_DIM,
    MTAD_GAT_ALPHA,
    MTAD_GAT_EPOCHS,
    MTAD_GAT_VAL_SPLIT,
    MTAD_GAT_BS,
    MTAD_GAT_INIT_LR,
    MTAD_GAT_SHUFFLE_DATASET,
    MTAD_GAT_DROPOUT,
    MTAD_GAT_USE_CUDA,
    MTAD_GAT_PRINT_EVERY,
    MTAD_GAT_LOG_TENSORBOARD,
    MTAD_GAT_SCALE_SCORES,
    MTAD_GAT_USE_MOV_AV,
    MTAD_GAT_GAMMA,
    MTAD_GAT_LEVEL,
    MTAD_GAT_Q,
    MTAD_GAT_DYNAMIC_POT,
    MTAD_GAT_THREADS
    #   MTAD_GAT_TYPE,
    #   MTAD_GAT_DEFAULT
]

MTAD_GAT_TARGET_DIMS = "target_dims"
MTAD_GAT_REG_LEVEL = "reg_level"

MTAD_GAT_PREDICTION_ARGUMENTS = [
    MTAD_GAT_TARGET_DIMS,
    MTAD_GAT_SCALE_SCORES,
    MTAD_GAT_LEVEL,
    MTAD_GAT_Q,
    MTAD_GAT_DYNAMIC_POT,
    MTAD_GAT_GAMMA,
    MTAD_GAT_USE_MOV_AV,
    MTAD_GAT_REG_LEVEL]


##  eval methods prediction

MTAD_GAT_POT_METHOD = 'pot'
MTAD_GAT_EPSILON_METHOD = 'epsilon'

## OUTPUT
MTAD_GAT_OUT_EPOCHS_IDS= "epochIds"

## prediction out args
MTAD_GAT_OUT_FORECAST_i="Forecast_{i}"
MTAD_GAT_OUT_RECON_i="Recon_{i}"
MTAD_GAT_OUT_TRUE_i="True_{i}"
MTAD_GAT_OUT_SCORE_i="A_Score_{i}"
MTAD_GAT_OUT_THRESHOLD_i="Thresh_{i}"
MTAD_GAT_OUT_PREDICTION_i="A_Pred_{i}"

MTAD_GAT_OUT_TRUE_GLOBAL="A_True_Global"
MTAD_GAT_OUT_THRESHOLD_GLOBAL="Thresh_Global"
MTAD_GAT_OUT_SCORE_GLOBAL='A_Score_Global'
MTAD_GAT_OUT_PREDICTION_GLOBAL="A_Pred_Global"
MTAD_GAT_OUT_WINDOW = "window"