settings:
  digits: 3
  prefix: MRS
  sep: '-'
  itemformat: markdown

attributes:
  defaults:
    type: 'F'
    rationale: ""
    importance: "5"
    urgency: "5"
    vm: 'T'
    release: "Alpha"
    text: |
      Description

      ## Rationale
      - 
      
      ## Acceptance criteria
    # the following are optional, uncomment as needed
    #risk: ''
    #difficulty: ''
    #subsystem: ""

  publish:
    - type
    - rationale
    - importance
    - urgency
    - vm
    - release
  
  reviewed:
    - type
    - rationale
    - importance
    - urgency
    - vm
    - release