from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import secrets
import string
import subprocess
import sys
from pathlib import Path
from typing import Callable, Optional

from wazuh_api import envfile

STOCK = {
    "OS_PASS": {"SecretPassword"},
    "WAZUH_AUTH_PASS": {"MyS3cr37P450r.*-", "wazuh-wui"},
    "DASHBOARD_PASS": {"SecretPassword"},
    "INDEXER_DASHBOARD_PASSWORD": {"kibanaserver"},
}
LEGACY_DEFAULTS = {"OS_PASS": "SecretPassword", "WAZUH_AUTH_PASS": "MyS3cr37P450r.*-",
                   "INDEXER_DASHBOARD_PASSWORD": "kibanaserver"}
GENERATED_DIR = ".radar-generated"
_BCRYPT_RE = re.compile(r"^\$2[aby]\$\d\d\$[./A-Za-z0-9]{53}$")
_JAVA_HOME = "/usr/share/wazuh-indexer/jdk"
_HASH_SH = "/usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh"
_SECURITYADMIN = "/usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh"
_CERTS = "/usr/share/wazuh-indexer/config/certs"


def generate_password() -> str:
    alphabet = string.ascii_letters + string.digits
    while True:
        core = "".join(secrets.choice(alphabet) for _ in range(28))
        if any(c.islower() for c in core) and any(c.isupper() for c in core) and any(c.isdigit() for c in core):
            return core + ".-"


def _say(msg: str) -> None:
    print(msg, flush=True)


def indexer_image(radar_root: Path) -> str:
    text = (radar_root / "docker-compose.core.yml").read_text()
    m = re.search(r"image:\s*(wazuh/wazuh-indexer:\S+)", text)
    return m.group(1) if m else "wazuh/wazuh-indexer:4.14.1"


def compose_project_name(radar_root: Path) -> str:
    name = os.environ.get("COMPOSE_PROJECT_NAME") or envfile.load(radar_root / ".env").get("COMPOSE_PROJECT_NAME", "")
    if not name:
        name = re.sub(r"[^a-z0-9_-]", "", radar_root.resolve().name.lower()).lstrip("_-")
    return name


def indexer_volume_exists(radar_root: Path) -> Optional[bool]:
    volume = f"{compose_project_name(radar_root)}_wazuh-indexer-data"
    try:
        proc = subprocess.run(["docker", "volume", "inspect", volume], capture_output=True, text=True, timeout=20)
    except Exception:
        return None
    if proc.returncode == 0:
        return True
    if "no such volume" in (proc.stderr or "").lower():
        return False
    return None


def container_running(name: str) -> bool:
    try:
        out = subprocess.run(["docker", "ps", "--format", "{{.Names}}"], capture_output=True, text=True,
                             timeout=20, check=True).stdout
    except Exception:
        return False
    return name in out.split()


def bcrypt_hash(password: str, radar_root: Path, container: Optional[str] = None) -> str:
    try:
        import bcrypt  # type: ignore
        return bcrypt.hashpw(password.encode(), bcrypt.gensalt(12)).decode()
    except ImportError:
        pass
    script = f'export JAVA_HOME={_JAVA_HOME}; bash {_HASH_SH} -p "$RADAR_HASH_PW"'
    env = {**os.environ, "RADAR_HASH_PW": password}
    if container:
        cmd = ["docker", "exec", "-e", "RADAR_HASH_PW", container, "bash", "-c", script]
    else:
        cmd = ["docker", "run", "--rm", "-e", "RADAR_HASH_PW", "--entrypoint", "bash",
               indexer_image(radar_root), "-c", script]
    proc = subprocess.run(cmd, capture_output=True, text=True, env=env, timeout=300)
    for line in reversed((proc.stdout or "").splitlines()):
        if _BCRYPT_RE.match(line.strip()):
            return line.strip()
    raise RuntimeError(f"could not hash a password with the indexer's hash.sh: {(proc.stderr or proc.stdout)[-400:]}")


def _fingerprint(*values: str) -> str:
    return hashlib.sha256("\0".join(values).encode()).hexdigest()


def internal_users_yaml(admin_hash: str, kibanaserver_hash: str, fingerprint: str) -> str:
    return f"""---
# Generated by wazuh_api/credentials.py (security audit #4). Do not edit or
# commit; regenerated when OS_PASS / INDEXER_DASHBOARD_PASSWORD change.
# radar-fingerprint: {fingerprint}
_meta:
  type: "internalusers"
  config_version: 2

admin:
  hash: "{admin_hash}"
  reserved: true
  backend_roles:
  - "admin"
  description: "Indexer admin (RADAR)"

kibanaserver:
  hash: "{kibanaserver_hash}"
  reserved: true
  description: "Dashboard server user (RADAR)"
"""


def wazuh_yml(user: str, password: str) -> str:
    return f"""# Generated by wazuh_api/credentials.py (security audit #4). Do not edit.
hosts:
  - 1513629884013:
      url: "https://wazuh.manager"
      port: 55000
      username: {json.dumps(user)}
      password: {json.dumps(password)}
      run_as: false
"""


def _gen_dir(radar_root: Path) -> Path:
    d = radar_root / GENERATED_DIR
    d.mkdir(mode=0o700, exist_ok=True)
    os.chmod(d, 0o700)
    gi = d / ".gitignore"
    if not gi.exists():
        gi.write_text("*\n")
    return d


def write_generated(radar_root: Path, env: dict, hasher: Callable[[str], str], force_users: bool = False) -> None:
    d = _gen_dir(radar_root)
    fp = _fingerprint(env["OS_PASS"], env["INDEXER_DASHBOARD_PASSWORD"])
    users = d / "internal_users.yml"
    current = users.read_text() if users.exists() else ""
    if force_users or f"radar-fingerprint: {fp}" not in current:
        text = internal_users_yaml(hasher(env["OS_PASS"]), hasher(env["INDEXER_DASHBOARD_PASSWORD"]), fp)
        envfile.write_atomic(users, text, mode=0o644)
    envfile.write_atomic(d / "wazuh.yml", wazuh_yml(env.get("WAZUH_AUTH_USER") or "wazuh-wui", env["WAZUH_AUTH_PASS"]),
                         mode=0o644)


def plan_ensure(env: dict, fresh: bool) -> tuple[dict, list[str]]:
    updates, warnings = {}, []
    os_user = env.get("OS_USER") or "admin"
    if not env.get("OS_USER"):
        updates["OS_USER"] = "admin"
    if not env.get("WAZUH_AUTH_USER"):
        updates["WAZUH_AUTH_USER"] = "wazuh-wui"
    for key in ("OS_PASS", "WAZUH_AUTH_PASS", "INDEXER_DASHBOARD_PASSWORD"):
        value = env.get(key, "")
        if fresh and (not value or value in STOCK[key]):
            updates[key] = generate_password()
        elif not value:
            updates[key] = LEGACY_DEFAULTS[key]
            warnings.append(f"{key} was missing; set to the stock value the running stack uses")
    new_os_pass = updates.get("OS_PASS", env.get("OS_PASS", ""))
    if (env.get("DASHBOARD_USER") or "admin") == os_user and (
            not env.get("DASHBOARD_PASS") or env.get("DASHBOARD_PASS") in STOCK["DASHBOARD_PASS"]
            or "OS_PASS" in updates):
        if env.get("DASHBOARD_PASS") != new_os_pass:
            updates["DASHBOARD_PASS"] = new_os_pass
    if os_user != "admin":
        warnings.append("OS_USER is not 'admin': the bundled indexer's admin password is still taken from OS_PASS")
    final = {**env, **updates}
    stock_left = [k for k in ("OS_PASS", "WAZUH_AUTH_PASS", "INDEXER_DASHBOARD_PASSWORD") if final.get(k) in STOCK[k]]
    if stock_left:
        warnings.append("stock default credentials still in use (" + ", ".join(stock_left)
                        + "): run 'sudo ./radar.sh rotate-credentials'")
    return updates, warnings


def ensure(radar_root: Path, hasher: Optional[Callable[[str], str]] = None) -> int:
    env_path = radar_root / ".env"
    env = envfile.load(env_path)
    exists = indexer_volume_exists(radar_root)
    fresh = exists is False
    if exists is None:
        _say("[!] could not query docker volumes; treating this as an existing deployment (no password changes)")
    elif exists:
        _say(f"OK - existing deployment ({compose_project_name(radar_root)}_wazuh-indexer-data found): passwords left unchanged")
    updates, warnings = plan_ensure(env, fresh)
    if updates:
        envfile.update(env_path, updates)
        generated = sorted(k for k in updates if k.endswith(("PASS", "PASSWORD"))
                           and updates[k] not in LEGACY_DEFAULTS.values())
        if generated:
            _say(f"OK - generated unique credentials in .env: {', '.join(generated)}")
    env = {**env, **updates}
    write_generated(radar_root, env, hasher or (lambda pw: bcrypt_hash(pw, radar_root)))
    _say("OK - wrote .radar-generated/internal_users.yml and wazuh.yml")
    for w in warnings:
        _say(f"[!] {w}")
    return 0


def rotate(radar_root: Path, indexer: str = "wazuh.indexer", manager: str = "wazuh.manager") -> int:
    env_path = radar_root / ".env"
    env = envfile.load(env_path)
    if (env.get("OS_USER") or "admin") != "admin":
        _say("[ERROR] OS_USER is not 'admin'; rotate-credentials only manages the bundled indexer's admin user")
        return 2
    for c in (indexer, manager):
        if not container_running(c):
            _say(f"[ERROR] container {c} is not running; start the core stack first")
            return 2
    new = {
        "OS_PASS": generate_password(),
        "WAZUH_AUTH_PASS": generate_password(),
        "INDEXER_DASHBOARD_PASSWORD": generate_password(),
    }
    if (env.get("DASHBOARD_USER") or "admin") == "admin":
        new["DASHBOARD_PASS"] = new["OS_PASS"]
    staged = {**env, **new, "WAZUH_AUTH_USER": env.get("WAZUH_AUTH_USER") or "wazuh-wui"}

    d = _gen_dir(radar_root)
    staging = d / "internal_users.rotating.yml"
    hasher = lambda pw: bcrypt_hash(pw, radar_root, container=indexer)  # noqa: E731
    fp = _fingerprint(staged["OS_PASS"], staged["INDEXER_DASHBOARD_PASSWORD"])
    envfile.write_atomic(staging, internal_users_yaml(hasher(staged["OS_PASS"]),
                                                      hasher(staged["INDEXER_DASHBOARD_PASSWORD"]), fp), mode=0o644)
    _say(">>> Applying new indexer users with securityadmin.sh (demo users are removed)...")
    tmp_in = "/tmp/radar-internal_users.yml"
    subprocess.run(["docker", "cp", str(staging), f"{indexer}:{tmp_in}"], check=True, timeout=30)
    script = (f"export JAVA_HOME={_JAVA_HOME}; bash {_SECURITYADMIN} -f {tmp_in} -t internalusers "
              f"-icl -nhnv -cacert {_CERTS}/root-ca.pem -cert {_CERTS}/admin.pem -key {_CERTS}/admin-key.pem "
              f"-h localhost -p 9200")
    proc = subprocess.run(["docker", "exec", indexer, "bash", "-c", script], capture_output=True, text=True,
                          timeout=300)
    subprocess.run(["docker", "exec", "-u", "0", indexer, "rm", "-f", tmp_in], capture_output=True, timeout=30)
    if proc.returncode != 0 or "Done with success" not in (proc.stdout or ""):
        staging.unlink(missing_ok=True)
        _say("[ERROR] securityadmin.sh failed; nothing was changed:\n" + (proc.stdout + proc.stderr)[-1500:])
        return 1

    backup = radar_root / ".radar-state"
    backup.mkdir(mode=0o700, exist_ok=True)
    envfile.write_atomic(backup / "env.before-rotation", env_path.read_text(), mode=0o600)
    envfile.update(env_path, {**new, "WAZUH_AUTH_USER": staged["WAZUH_AUTH_USER"]})
    os.replace(staging, d / "internal_users.yml")
    envfile.write_atomic(d / "wazuh.yml", wazuh_yml(staged["WAZUH_AUTH_USER"], staged["WAZUH_AUTH_PASS"]), mode=0o644)
    _say("OK - indexer users rotated; .env updated (previous copy: .radar-state/env.before-rotation)")
    return 0


def _cli(argv) -> int:
    ap = argparse.ArgumentParser(prog="python3 -m wazuh_api.credentials")
    ap.add_argument("command", choices=["ensure", "rotate"])
    ap.add_argument("--radar-root", default=".")
    ap.add_argument("--indexer", default="wazuh.indexer")
    ap.add_argument("--manager", default="wazuh.manager")
    a = ap.parse_args(argv)
    root = Path(a.radar_root).resolve()
    if a.command == "ensure":
        return ensure(root)
    return rotate(root, a.indexer, a.manager)


if __name__ == "__main__":
    sys.exit(_cli(sys.argv[1:]))
