FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies and Wazuh Agent from official APT repo
RUN apt update && apt install -y \
    curl gnupg apt-transport-https lsb-release procps strace \
 && curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --dearmor -o /usr/share/keyrings/wazuh-archive-keyring.gpg \
 && echo "deb [signed-by=/usr/share/keyrings/wazuh-archive-keyring.gpg] https://packages.wazuh.com/4.x/apt/ stable main" \
    > /etc/apt/sources.list.d/wazuh.list \
 && apt update && apt install -y wazuh-agent=4.12.0-1

COPY audit.rules /etc/audit/rules.d/audit.rules

# Default command
CMD ["/bin/bash", "-c", "auditctl -s && /bin/bash"]

