version: '3.7'

# networks:
#   soar-radar:
#     driver: bridge

services:
  agent.insider:
    build:
      context: insider_threat
      dockerfile: Dockerfile.agent
    container_name: agent.insider
    privileged: true
    # networks:
    #   - soar-radar
    tty: true
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./config/wazuh_agent/local_internal_options.conf:/wazuh-config-mount/etc/local_internal_options.conf

  agent.ddos:
    build:
      context: ddos_detection
      dockerfile: Dockerfile.agent
    container_name: agent.ddos
    # networks:
    #   - soar-radar
    tty: true
    ports:
      - "8800:80"
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./config/wazuh_agent/local_internal_options.conf:/wazuh-config-mount/etc/local_internal_options.conf

  agent.malcom:
    build:
      context: malware_communication
      dockerfile: Dockerfile.agent
    container_name: agent.malcom
    # networks:
    #   - soar-radar
    tty: true
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - ./config/wazuh_agent/local_internal_options.conf:/wazuh-config-mount/etc/local_internal_options.conf

  agent.suspicious:
    build:
      context: suspicious_login
      dockerfile: Dockerfile.agent
    container_name: agent.suspicious
    restart: always
    # networks:
    #   - soar-radar
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=secret
    command: start-dev
    volumes:
      - ./config/wazuh_agent/local_internal_options.conf:/wazuh-config-mount/etc/local_internal_options.conf

  agent.geoip:
    build:
      context: geoip_detection
      dockerfile: Dockerfile.agent
    container_name: agent.geoip
    # networks:
    #   - soar-radar
    tty: true
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - ./config/wazuh_agent/local_internal_options.conf:/wazuh-config-mount/etc/local_internal_options.conf

  agent.logvolume:
    build:
      context: log_volume
      dockerfile: Dockerfile.agent
    container_name: agent.logvolume
    # networks:
    #   - soar-radar
    tty: true
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
      - ./config/wazuh_agent/local_internal_options.conf:/wazuh-config-mount/etc/local_internal_options.conf
