---

- name: Configure Wazuh Manager for scenario
  hosts: "wazuh_manager_local,wazuh_manager_ssh"
  gather_facts: false
  vars:
    scenario_path: "{{ scenario_name }}"
    os_user: "{{ lookup('env', 'OS_USER') }}"
    os_pass: "{{ lookup('env', 'OS_PASS') }}"
    indexer_host: "{{ lookup('env', 'OS_URL') }}"
  roles:
    - wazuh_manager

- name: Install and configure Wazuh Agents
  hosts: "wazuh_agents_container,wazuh_agents_ssh"
  vars:
    scenario_path: "{{ scenario_name }}"
  roles:
    - wazuh_agent
