#!/usr/bin/env bash
set -Eeuo pipefail

RADAR_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VOLUMES_YML="$RADAR_ROOT/volumes.yml"

# shellcheck source=./_lib.sh
source "$RADAR_ROOT/radar_deploy/_lib.sh"
radar_load_env "$RADAR_ROOT"

hostpath() { grep -E ":${1//\//\\/}\$" "$VOLUMES_YML" | head -1 | sed -E 's/^ *- *//; s/:[^:]*$//'; }
OSSEC_ETC=$(hostpath '/var/ossec/etc')
OSSEC_CONF="$OSSEC_ETC/ossec.conf"

if [[ ! -f "$OSSEC_CONF" ]]; then
  echo "[!] ossec.conf not found at $OSSEC_CONF -- skipping enrollment hardening"
  exit 0
fi

PRE_HASH=$(md5sum "$OSSEC_CONF" | awk '{print $1}')

sed -i 's/<use_password>no<\/use_password>/<use_password>yes<\/use_password>/' "$OSSEC_CONF"
sed -i 's/<purge>yes<\/purge>/<purge>no<\/purge>/' "$OSSEC_CONF"

if [[ -z "${WAZUH_CLUSTER_KEY:-}" ]]; then
  WAZUH_CLUSTER_KEY="$(head -c 24 /dev/urandom | md5sum | cut -d' ' -f1)"
  echo ">>> WAZUH_CLUSTER_KEY not set in .env -- generating one and persisting it there."
  { echo ""; echo "# Generated by manager-harden-enrollment.sh -- do not commit this file."; \
    echo "WAZUH_CLUSTER_KEY=${WAZUH_CLUSTER_KEY}"; } >> "$RADAR_ROOT/.env"
fi
sed -i "/<cluster>/,/<\/cluster>/ s|<key>[^<]*</key>|<key>${WAZUH_CLUSTER_KEY}</key>|" "$OSSEC_CONF"

POST_HASH=$(md5sum "$OSSEC_CONF" | awk '{print $1}')

if [[ "$PRE_HASH" != "$POST_HASH" ]]; then
  echo "OK - hardened enrollment: use_password=yes, purge=no, cluster key set"
else
  echo "OK - enrollment already hardened (or tags not found in ossec.conf)"
fi

if [[ $EUID -eq 0 ]]; then
  bash "$RADAR_ROOT/radar_deploy/manager-enrollment-window.sh" close
else
  echo "[!] Not running as root: skipping the port 1515 firewall check."
fi